import type { SimulationData } from "./index"

export const simulation3: SimulationData = {
  id: 3,
  title: "Siguria e Server Room",
  description: "Menaxhimi i sigurisë fizike dhe logjike të server room",
  icon: "Server",
  context: "Ju jeni administrator i server room në shkollë dhe menaxhoni sigurinë e pajisjeve.",
  steps: [
    {
      id: 1,
      type: "situate",
      location: "serveroom",
      content: "Vëreni që dera e server room nuk ka kyç elektronik dhe çdokush mund të hyjë.",
      question: "Cili është veprimi i parë?",
      options: [
        { id: 1, text: "E lë si është sepse janë kolegë", correct: false },
        { id: 2, text: "Kërkoi instalimin e sistemit të qasjes me kartë/kod dhe kamerë sigurie", correct: true },
        { id: 3, text: "Vendos një fletë 'Mos hyr'", correct: false },
        { id: 4, text: "Mbyll derën me çelës personal", correct: false },
      ],
      explanation: "Qasja fizike në server room duhet kontrolluar rreptësisht me sisteme elektronike.",
    },
    {
      id: 2,
      type: "ndodhi",
      location: "serveroom",
      content: "Gjatë një kontrolli rutinë, gjeni një laptop personal të lidhur në rrjetin e serverave.",
      question: "Çfarë bëni?",
      options: [
        { id: 1, text: "E lë sepse mund të jetë i dikujt", correct: false },
        { id: 2, text: "E shkëput nga rrjeti, dokumentoj dhe hetoj kush e la atje", correct: true },
        { id: 3, text: "E përdor për punë", correct: false },
        { id: 4, text: "E vendos në një cep", correct: false },
      ],
      explanation: "Pajisjet e paautorizuara në rrjetin e serverave janë rrezik i madh sigurie.",
    },
    {
      id: 3,
      type: "mesazh",
      location: "security",
      content: "Merrni alarm: 'UPS battery low - 15 minutes remaining'. Nuk ka gjenerator backup.",
      question: "Si reagoni?",
      options: [
        { id: 1, text: "Pres derisa të kthehet energjia", correct: false },
        { id: 2, text: "Filloj shutdown të rregullt të serverave jo-kritikë dhe kontaktoj furnizuesin", correct: true },
        { id: 3, text: "Shkëput të gjithë serverët menjëherë", correct: false },
        { id: 4, text: "Injoroj alarmin", correct: false },
      ],
      explanation: "Shutdown i rregullt parandalon humbjen e të dhënave. Serverët kritikë duhet të kenë prioritet.",
    },
    {
      id: 4,
      type: "telefonata",
      location: "serveroom",
      content:
        "Dikush telefonon duke thënë se është teknik i kontraktuar për mirëmbajtje dhe kërkon qasje remote në servera.",
      question: "Si veproni?",
      options: [
        { id: 1, text: "I jap qasje remote menjëherë", correct: false },
        { id: 2, text: "Verifikoj me menaxherin dhe kompaninë e kontraktuar para se të jap qasje", correct: true },
        { id: 3, text: "I jap vetëm lexim, jo shkrim", correct: false },
        { id: 4, text: "I them të vijë personalisht", correct: false },
      ],
      explanation: "Çdo kërkesë për qasje duhet verifikuar nëpërmit kanaleve zyrtare.",
    },
    {
      id: 5,
      type: "pyetje",
      location: "laborator",
      content: "Drejtori pyet: 'A kemi backup të të dhënave? Sa shpesh bëhen?'",
      question: "Cila është praktika më e mirë që rekomandoni?",
      options: [
        { id: 1, text: "Backup manual kur kemi kohë", correct: false },
        { id: 2, text: "Backup automatik ditor, javor i plotë, dhe offsite storage", correct: true },
        { id: 3, text: "Backup vetëm kur ndryshojnë skedarët", correct: false },
        { id: 4, text: "Nuk nevojiten backup, serverët janë të sigurt", correct: false },
      ],
      explanation: "Strategjia 3-2-1 backup është standardi: 3 kopje, 2 media të ndryshme, 1 offsite.",
    },
    {
      id: 6,
      type: "situate",
      location: "serveroom",
      content: "Sistemi HVAC i server room ka dështuar dhe temperatura po rritet në 35°C.",
      question: "Çfarë veprimi merrni?",
      options: [
        { id: 1, text: "Pres derisa të riparohet HVAC", correct: false },
        { id: 2, text: "Hap derën për ventilim, uli ngarkesën dhe kontaktoj mirëmbajtjen urgjent", correct: true },
        { id: 3, text: "Fik serverët menjëherë", correct: false },
        { id: 4, text: "Instaloj ventilatorë portativë", correct: false },
      ],
      explanation: "Temperatura e lartë dëmton hardwarin. Duhet marrë masa të menjëhershme për ftohje.",
    },
    {
      id: 7,
      type: "ndodhi",
      location: "serveroom",
      content: "Vëreni që një hard disk në RAID array po tregon dritë portokalli (warning).",
      question: "Çfarë bëni?",
      options: [
        { id: 1, text: "Pres derisa të dështojë plotësisht", correct: false },
        { id: 2, text: "Porosis zëvendësim, verifikoj backup-et dhe planifikoj ndërrimin", correct: true },
        { id: 3, text: "E heq diskun menjëherë", correct: false },
        { id: 4, text: "Ristarton serverin", correct: false },
      ],
      explanation: "Disku me warning duhet zëvendësuar para dështimit. RAID nuk është backup.",
    },
    {
      id: 8,
      type: "tekst",
      location: "ambjent",
      content: "Një koleg kërkon të instalojë softuer personal në serverin e printimit 'për punë më të lehtë'.",
      question: "Si përgjigjeni?",
      options: [
        { id: 1, text: "E lejoj sepse është koleg", correct: false },
        { id: 2, text: "Refuzoj - vetëm softuer i autorizuar instalohet në servera", correct: true },
        { id: 3, text: "E lejoj por e monitoroj", correct: false },
        { id: 4, text: "I them ta instalojë vetë", correct: false },
      ],
      explanation: "Instalimi i softuerit të paautorizuar në servera rrit rrezikun e sigurisë.",
    },
    {
      id: 9,
      type: "mesazh",
      location: "security",
      content: "Loget tregojnë 50 përpjekje të dështuara login në serverin e domainit në 5 minuta.",
      question: "Si reagoni?",
      options: [
        { id: 1, text: "Injoroj sepse login dështoi", correct: false },
        { id: 2, text: "Bllokoj IP-në source, verifikoj nëse llogaria target u kompromitua", correct: true },
        { id: 3, text: "Ndërroj fjalëkalimin e administratorit", correct: false },
        { id: 4, text: "Ristarton serverin", correct: false },
      ],
      explanation: "Përpjekjet e shumta login tregojnë sulm brute-force. IP duhet bllokuar menjëherë.",
    },
    {
      id: 10,
      type: "situate",
      location: "pajisje",
      content: "Zbulohet që backup-et e fundit 30 ditëve janë korruptuar dhe nuk mund të restaurohen.",
      question: "Çfarë masash parandaluese do të implementoni?",
      options: [
        { id: 1, text: "Shpresoj që nuk do të ketë nevojë për restore", correct: false },
        { id: 2, text: "Implementoj verifikim automatik të backup-eve dhe teste restore periodike", correct: true },
        { id: 3, text: "Rris frekuencën e backup", correct: false },
        { id: 4, text: "Ndërroj softuerin e backup", correct: false },
      ],
      explanation: "Backup-et duhet testuar rregullisht. Backup i pa-testuar nuk është backup.",
    },
  ],
  testQuestions: [
    {
      id: 1,
      question: "Çfarë është RAID?",
      options: [
        { id: 1, text: "Lloj backup", correct: false },
        { id: 2, text: "Lloj serveri", correct: false },
        { id: 3, text: "Teknologji për kombinimin e disqeve për performance dhe/ose redundancë", correct: true },
        { id: 4, text: "Softuer antivirus", correct: false },
      ],
    },
    {
      id: 2,
      question: "Çfarë është strategjia 3-2-1 e backup?",
      options: [
        { id: 1, text: "3 servera, 2 rrjete, 1 admin", correct: false },
        { id: 2, text: "3 kopje, 2 media të ndryshme, 1 offsite", correct: true },
        { id: 3, text: "3 ditë, 2 javë, 1 muaj", correct: false },
        { id: 4, text: "3 fjalëkalime, 2 përdorues, 1 server", correct: false },
      ],
    },
    {
      id: 3,
      question: "Pse është i rëndësishëm UPS për server room?",
      options: [
        { id: 1, text: "Për internet më të shpejtë", correct: false },
        { id: 2, text: "Për ftohje", correct: false },
        { id: 3, text: "Për ndriçim", correct: false },
        { id: 4, text: "Për të siguruar energji emergjence dhe shutdown të rregullt", correct: true },
      ],
    },
    {
      id: 4,
      question: "Cila temperaturë është ideale për server room?",
      options: [
        { id: 1, text: "30-35°C", correct: false },
        { id: 2, text: "18-24°C", correct: true },
        { id: 3, text: "10-15°C", correct: false },
        { id: 4, text: "Nuk ka rëndësi", correct: false },
      ],
    },
    {
      id: 5,
      question: "Çfarë duhet të bëni me hard disk që tregon warning?",
      options: [
        { id: 1, text: "Ta zëvendësojë para dështimit", correct: true },
        { id: 2, text: "Ta formatojë", correct: false },
        { id: 3, text: "Ta heqë menjëherë", correct: false },
        { id: 4, text: "Ta injorojë", correct: false },
      ],
    },
    {
      id: 6,
      question: "Pse nevojitet qasje e kontrolluar në server room?",
      options: [
        { id: 1, text: "Për të mbajtur pastërti", correct: false },
        { id: 2, text: "Për të parandaluar qasje fizike të paautorizuar", correct: true },
        { id: 3, text: "Për të kursyer energji", correct: false },
        { id: 4, text: "Për estetikë", correct: false },
      ],
    },
    {
      id: 7,
      question: "Sa shpesh duhet testuar backup-et?",
      options: [
        { id: 1, text: "Kurrë", correct: false },
        { id: 2, text: "Vetëm kur ka problem", correct: false },
        { id: 3, text: "Rregullisht, të paktën mujor", correct: true },
        { id: 4, text: "Një herë në vit", correct: false },
      ],
    },
    {
      id: 8,
      question: "Çfarë duhet të bëni para mirëmbajtjes nga teknikë të jashtëm?",
      options: [
        { id: 1, text: "Asgjë", correct: false },
        { id: 2, text: "Verifikoni identitetin dhe autorizimin", correct: true },
        { id: 3, text: "Jepni qasje totale", correct: false },
        { id: 4, text: "Largoheni nga server room", correct: false },
      ],
    },
    {
      id: 9,
      question: "Çfarë tregon sulmi brute-force në loge?",
      options: [
        { id: 1, text: "Përdorim normal", correct: false },
        { id: 2, text: "Login të suksesshme", correct: false },
        { id: 3, text: "Probleme rrjeti", correct: false },
        { id: 4, text: "Përpjekje të shumta login të dështuara në kohë të shkurtër", correct: true },
      ],
    },
    {
      id: 10,
      question: "Pse RAID nuk zëvendëson backup?",
      options: [
        { id: 1, text: "Sepse nuk mbron nga fshirja aksidentale ose ransomware", correct: true },
        { id: 2, text: "Sepse është i ngadaltë", correct: false },
        { id: 3, text: "RAID zëvendëson backup", correct: false },
        { id: 4, text: "Sepse është i shtrenjtë", correct: false },
      ],
    },
  ],
  elaborationQuestion: {
    question:
      "Përshkruani një plan të plotë të disaster recovery për server room të një shkolle. Përfshini backup, sigurinë fizike, dhe procedurat emergjente.",
    keywords: [
      "backup",
      "restore",
      "UPS",
      "gjenerator",
      "temperaturë",
      "HVAC",
      "RAID",
      "offsite",
      "test",
      "procedurë",
      "emergjencë",
      "qasje",
      "kamerë",
      "log",
      "monitoring",
    ],
  },
}
