import type { SimulationData } from "./index"

export const simulation5: SimulationData = {
  id: 5,
  title: "Malware dhe Mbrojtja e Pajisjeve",
  description: "Identifikimi dhe parandalimi i malware në pajisjet e shkollës",
  icon: "Bug",
  context: "Ju jeni përgjegjës për mbrojtjen e pajisjeve kompjuterike të shkollës nga malware.",
  steps: [
    {
      id: 1,
      type: "ndodhi",
      location: "laborator",
      content: "Një kompjuter në laborator fillon të hapë dritare pop-up të shumta dhe të ngadalësohet.",
      question: "Cili është hapi i parë?",
      options: [
        { id: 1, text: "Shkëput nga rrjeti, skanoj me antivirus dhe hetoj aktivitetin", correct: true },
        { id: 2, text: "Ristarton kompjuterin dhe vazhdoj punën", correct: false },
        { id: 3, text: "Instalon anti-pop-up", correct: false },
        { id: 4, text: "E lë të punojë sepse ende punon", correct: false },
      ],
      explanation: "Pop-up-et e shumta dhe ngadalësimi janë shenja malware. Izolimi është i parë.",
    },
    {
      id: 2,
      type: "mesazh",
      location: "security",
      content: "Antivirusi raporton: 'Trojan.GenericKD detected in system32 folder'.",
      question: "Çfarë veprimi merrni?",
      options: [
        { id: 1, text: "E injoroj sepse është në dosje sistemi", correct: false },
        { id: 2, text: "Karantinoj, skanoj plotësisht sistemin dhe verifikoj backup-et", correct: true },
        { id: 3, text: "Fshij dosjen system32", correct: false },
        { id: 4, text: "Ristarton dhe shpresoj të zhduket", correct: false },
      ],
      explanation: "Trojans në dosjet e sistemit janë seriozë. Skanimi i plotë dhe karantinim janë esenciale.",
    },
    {
      id: 3,
      type: "situate",
      location: "ambjent",
      content: "Ekrani i një kompjuteri shfaq: 'Files encrypted! Pay 500€ in Bitcoin to decrypt'.",
      question: "Si reagoni ndaj këtij ransomware?",
      options: [
        { id: 1, text: "Paguaj 500€ për të marrë skedarët", correct: false },
        { id: 2, text: "Ristarton kompjuterin", correct: false },
        { id: 3, text: "Shkëput nga rrjeti, mos paguaj, raportoj dhe restauroj nga backup", correct: true },
        { id: 4, text: "Pres disa ditë", correct: false },
      ],
      explanation: "Mos paguani kurrë ransom. Izolimi parandalon përhapjen dhe backup-i është zgjidhja.",
    },
    {
      id: 4,
      type: "telefonata",
      location: "laborator",
      content: "Një nxënës telefonon: 'Shkarkova një lojë falas dhe tani kompjuteri nuk punon mirë'.",
      question: "Çfarë e udhëzoni të bëjë?",
      options: [
        { id: 1, text: "Ta ristarton dhe të provon ende", correct: false },
        { id: 2, text: "Ta reinstalojë Windows", correct: true },
        { id: 3, text: "Ta fshijë lojën dhe të vazhdojë", correct: false },
        { id: 4, text: "Të mos e përdorin, ta sjellin për skanim dhe të mos shkarkojë softuer të paverifikuar", correct: false },
      ],
      explanation: "Softuer 'falas' shpesh përmban malware. Skanimi profesional është i nevojshëm.",
    },
    {
      id: 5,
      type: "pyetje",
      location: "laborator",
      content: "Mësuesi pyet: 'A mund të çaktivizoj antivirusin për të instaluar softuer që e bllokon?'",
      question: "Çfarë rekomandoni?",
      options: [
        { id: 1, text: "Po, çaktivizoje përkohësisht", correct: false },
        { id: 2, text: "Jo, nëse antivirusi e bllokon mund të jetë i rrezikshëm. Verifikoni burimin", correct: true },
        { id: 3, text: "Po, por riaktivizoje menjëherë", correct: false },
        { id: 4, text: "Instaloje në mënyrë tjetër", correct: false },
      ],
      explanation: "Antivirusi bllokon softuer potencialisht të rrezikshëm. Mos e anashkaloni.",
    },
    {
      id: 6,
      type: "ndodhi",
      location: "pajisje",
      content: "Gjeni softuer keylogger të instaluar në kompjuterin e zyrës së drejtorit.",
      question: "Çfarë veprimesh merrni?",
      options: [
        { id: 1,
          text: "Dokumentoj, ruaj evidence, heq keylogger, ndërroj të gjitha fjalëkalimet, raportoj",
          correct: true, },
        { id: 2, text: "E fshij dhe vazhdon punën", correct: false },
        { id: 3, text: "Ristarton kompjuterin", correct: false },
        { id: 4, text: "Instalon antivirus të ri", correct: false },
      ],
      explanation: "Keylogger tregon kompromitim serioz. Dokumentimi dhe ndërrimi i kredencialeve janë kritike.",
    },
    {
      id: 7,
      type: "situate",
      location: "laborator",
      content: "Vëreni që antivirusi i disa kompjuterëve nuk është përditësuar për 6 muaj.",
      question: "Pse është kjo problem dhe si e zgjidhni?",
      options: [
        { id: 1, text: "Nuk është problem sepse antivirusi ende punon", correct: false },
        { id: 2, text: "Ndërroj antivirusin", correct: false },
        { id: 3,
          text: "Antivirus i vjetër nuk njeh malware të ri. Përditësoj menjëherë dhe automatizoj",
          correct: true, },
        { id: 4, text: "Riinstaloj Windows", correct: false },
      ],
      explanation: "Përditësimet e antivirusit përmbajnë definicione për malware të ri.",
    },
    {
      id: 8,
      type: "mesazh",
      location: "security",
      content: "Task Manager tregon proces 'svchost32.exe' që konsumon 90% CPU dhe dërgon traffic në internet.",
      question: "A është kjo normale?",
      options: [
        { id: 1, text: "Jo, svchost32.exe mund të jetë malware që imiton procesin legjitime", correct: true },
        { id: 2, text: "Po, svchost është proces Windows", correct: false },
        { id: 3, text: "Po, por duhet ristaruar", correct: false },
        { id: 4, text: "Po, Windows po përditësohet", correct: false },
      ],
      explanation: "Procesi legjitime është svchost.exe jo svchost32.exe. Ky është malware i maskuar.",
    },
    {
      id: 9,
      type: "tekst",
      location: "ambjent",
      content: "Një koleg kërkon të shkarkojë 'crack' për softuer me pagesë 'për të kursyer buxhetin'.",
      question: "Si përgjigjeni?",
      options: [
        { id: 1, text: "E ndihmoj të gjejë crack", correct: false },
        { id: 2, text: "I jap licencën personale", correct: false },
        { id: 3, text: "E them ta shkarkojë në shtëpi", correct: false },
        { id: 4, text: "Refuzoj - crack shpesh përmban malware dhe shkel të drejtat e autorit", correct: true },
      ],
      explanation: "Softuer i piratuar shpesh përmban malware dhe shkel ligjet e të drejtave të autorit.",
    },
    {
      id: 10,
      type: "ndodhi",
      location: "serveroom",
      content: "Pas një infeksioni malware, zbulohet se ai u përhap në 5 kompjuterë të tjerë në rrjet.",
      question: "Çfarë masash parandaluese implementoni për të ardhmen?",
      options: [
        { id: 1, text: "Asnjë, infeksionet janë të pashmangshme", correct: false },
        { id: 2, text: "Segmentim rrjeti, përditësime automatike, EDR, dhe trajnim përdoruesish", correct: true },
        { id: 3, text: "Shtoj ende antivirus", correct: false },
        { id: 4, text: "Bllokoj internetin", correct: false },
      ],
      explanation: "Mbrojtja me shtresa parandalon përhapjen: segmentim, përditësime, EDR, edukim.",
    },
  ],
  testQuestions: [
    {
      id: 1,
      question: "Çfarë është ransomware?",
      options: [
        { id: 1, text: "Softuer për organizimin e skedarëve", correct: false },
        { id: 2, text: "Malware që enkripton skedarët dhe kërkon pagesë", correct: true },
        { id: 3, text: "Antivirus", correct: false },
        { id: 4, text: "Backup softuer", correct: false },
      ],
    },
    {
      id: 2,
      question: "Çfarë duhet të bëni nëse infektoheni me ransomware?",
      options: [
        { id: 1, text: "Paguaj ransom-in", correct: false },
        { id: 2, text: "Ristarton kompjuterin", correct: false },
        { id: 3, text: "Izoloj, mos paguaj, raportoj dhe restauroj nga backup", correct: true },
        { id: 4, text: "Pres të skadojë", correct: false },
      ],
    },
    {
      id: 3,
      question: "Çfarë është keylogger?",
      options: [
        { id: 1, text: "Tastierë speciale", correct: false },
        { id: 2, text: "Shortcut tastiere", correct: false },
        { id: 3, text: "Password manager", correct: false },
        { id: 4, text: "Malware që regjistron çdo tast që shtypni", correct: true },
      ],
    },
    {
      id: 4,
      question: "Pse janë të rrezikshme softuerët crack/pirat?",
      options: [
        { id: 1, text: "Sepse janë të mëdhenj", correct: false },
        { id: 2, text: "Sepse shpesh përmbajnë malware", correct: true },
        { id: 3, text: "Sepse janë të ngadaltë", correct: false },
        { id: 4, text: "Nuk janë të rrezikshme", correct: false },
      ],
    },
    {
      id: 5,
      question: "Çfarë duhet të bëni nëse antivirusi bllokon softuer?",
      options: [
        { id: 1, text: "Verifikoj burimin e softuerit para se të vendosni", correct: true },
        { id: 2, text: "E instaloj gjithsesi", correct: false },
        { id: 3, text: "Ndërroj antivirusin", correct: false },
        { id: 4, text: "Çaktivizoj antivirusin", correct: false },
      ],
    },
    {
      id: 6,
      question: "Çfarë është EDR?",
      options: [
        { id: 1, text: "Email service", correct: false },
        { id: 2, text: "Endpoint Detection and Response - mbrojtje e avancuar e pajisjeve", correct: true },
        { id: 3, text: "Lloj malware", correct: false },
        { id: 4, text: "Backup softuer", correct: false },
      ],
    },
    {
      id: 7,
      question: "Pse duhet përditësuar antivirusi rregullisht?",
      options: [
        { id: 1, text: "Për estetikë", correct: false },
        { id: 2, text: "Për shpejtësi", correct: false },
        { id: 3, text: "Për të njohur malware të ri", correct: true },
        { id: 4, text: "Nuk nevojitet", correct: false },
      ],
    },
    {
      id: 8,
      question: "Çfarë tregon procesi 'svchost32.exe'?",
      options: [
        { id: 1, text: "Proces normal Windows", correct: false },
        { id: 2, text: "Mundësi malware që imiton procesin legjitime", correct: true },
        { id: 3, text: "Përditësim sistemi", correct: false },
        { id: 4, text: "Antivirus", correct: false },
      ],
    },
    {
      id: 9,
      question: "Si parandaloni përhapjen e malware në rrjet?",
      options: [
        { id: 1, text: "Duke fikur kompjuterët", correct: false },
        { id: 2, text: "Duke pritur", correct: false },
        { id: 3, text: "Duke injoruar", correct: false },
        { id: 4, text: "Segmentim rrjeti, izolim i shpejtë, përditësime", correct: true },
      ],
    },
    {
      id: 10,
      question: "Çfarë duhet të bëni pas heqjes së malware?",
      options: [
        { id: 1, text: "Ndërro fjalëkalimet, verifiko backup-et, monitoroj për aktivitet të dyshimtë", correct: true },
        { id: 2, text: "Ristarton vetëm", correct: false },
        { id: 3, text: "Fshij antivirusin", correct: false },
        { id: 4, text: "Asgjë", correct: false },
      ],
    },
  ],
  elaborationQuestion: {
    question:
      "Përshkruani një strategji të plotë të mbrojtjes nga malware për shkollën. Përfshini parandalimin, zbulimin dhe reagimin.",
    keywords: [
      "antivirus",
      "përditësim",
      "skanim",
      "karantin",
      "backup",
      "izolim",
      "segmentim",
      "EDR",
      "trajnim",
      "ransomware",
      "phishing",
      "firewall",
      "monitoring",
      "raportim",
      "restore",
    ],
  },
}
