import type { SimulationData } from "./index"

export const simulation7: SimulationData = {
  id: 7,
  title: "Social Engineering dhe Ndërgjegjësimi",
  description: "Njohja dhe parandalimi i sulmeve social engineering",
  icon: "Users",
  context: "Ju jeni trajner sigurie dhe duhet të edukoni stafin për sulmet social engineering.",
  steps: [
    {
      id: 1,
      type: "telefonata",
      location: "laborator",
      content:
        "Dikush telefonon duke thënë se është 'teknik Microsoft' dhe kompjuteri i shkollës ka virus. Kërkon qasje remote.",
      question: "Çfarë lloj sulmi është ky dhe si reagoni?",
      options: [
        { id: 1, text: "Tech support scam - mbyll telefonin pa dhënë asnjë informacion", correct: true },
        { id: 2, text: "Ndihmë legjitime - jap qasje", correct: false },
        { id: 3, text: "I jap email për ta kontaktuar më vonë", correct: false },
        { id: 4, text: "I them ta telefonojë drejtorin", correct: false },
      ],
      explanation: "Microsoft nuk telefonon kurrë pa kërkesën tuaj. Ky është scam i zakonshëm.",
    },
    {
      id: 2,
      type: "situate",
      location: "ambjent",
      content: "Dikush me uniformë 'tekniku' kërkon të hyjë në server room 'për riparime urgjente' pa dokumentacion.",
      question: "Si veproni?",
      options: [
        { id: 1, text: "E lejoj sepse duket profesionist", correct: false },
        {
          id: 2,
          text: "Verifikoj identitetin, dokumentacionin dhe konfirmoj me menaxherin para se të lejoj akses",
          correct: true,
        },
        { id: 3, text: "E lejoj por e shoqëroj", correct: false },
        { id: 4, text: "I them të presë pa verifikuar", correct: false },
      ],
      explanation: "Sulmet 'pretexting' përdorin role false. Verifikimi është gjithmonë i domosdoshëm.",
    },
    {
      id: 3,
      type: "mesazh",
      location: "laborator",
      content:
        "Merrni email 'urgjent' nga 'drejtori' (adresë e ngjashme por jo e saktë) që kërkon transfer parash menjëherë.",
      question: "Çfarë lloj sulmi është ky?",
      options: [
        { id: 1, text: "Email legjitime nga drejtori", correct: false },
        { id: 2, text: "Spam i zakonshëm", correct: false },
        { id: 3, text: "CEO Fraud / Business Email Compromise - verifikoni nëpër kanali tjetër", correct: true },
        { id: 4, text: "Gabim teknik", correct: false },
      ],
      explanation: "CEO Fraud përdor urgjencë dhe autoritet false. Verifikoni gjithmonë nëpër telefoni.",
    },
    {
      id: 4,
      type: "ndodhi",
      location: "ambjent",
      content: "Gjeni USB në parkimin e shkollës me etiketë 'KONFIDENCIAL - PAGA MËSUESVE'.",
      question: "Çfarë taktike social engineering përdoret këtu?",
      options: [
        { id: 1, text: "Asgjë e dyshimtë - kontrollo përmbajtjen", correct: false },
        { id: 2, text: "USB e humbur - ruaje", correct: false },
        { id: 3, text: "USB normale që duhet kthyer", correct: false },
        { id: 4, text: "Baiting - USB mund të ketë malware. Dorëzo tek IT pa e futur", correct: true },
      ],
      explanation: "Baiting përdor kuriozitetin. USB të panjohura mund të përmbajnë malware.",
    },
    {
      id: 5,
      type: "pyetje",
      location: "laborator",
      content:
        "Koleg ju pyet: 'Dikush në LinkedIn më ofroi punë me pagë të lartë. Duhet vetëm të plotësoj disa të dhëna personale.'",
      question: "Çfarë këshille i jepni?",
      options: [
        { id: 1, text: "Ta pranojë menjëherë", correct: false },
        {
          id: 2,
          text: "Të verifikojë kompaninë, të mos japë të dhëna personale pa verifikim, të dyshojë oferta 'shumë të mira'",
          correct: true,
        },
        { id: 3, text: "Ti japë vetëm emailin", correct: false },
        { id: 4, text: "Ta injoroj ofertën", correct: false },
      ],
      explanation: "Job scams përdorin oferta joshëse për të vjedhur të dhëna personale.",
    },
    {
      id: 6,
      type: "tekst",
      location: "security",
      content: "Merrni SMS: 'Paketa juaj po mbahet në doganë. Klikoni për të paguar 5€ taksë: bit.ly/xxxxx'",
      question: "Çfarë lloj sulmi është ky?",
      options: [
        { id: 1, text: "Njoftim legjitime", correct: false },
        { id: 2, text: "Gabim doganor", correct: false },
        { id: 3, text: "Smishing (SMS phishing) - mos kliko, fshije", correct: true },
        { id: 4, text: "Reklamë", correct: false },
      ],
      explanation: "Smishing përdor SMS për phishing. Linket e shkurtuara janë veçanërisht të rrezikshme.",
    },
    {
      id: 7,
      type: "situate",
      location: "laborator",
      content: "Dikush hyn prapa jush kur hapni derën me kartë dhe thotë 'Harrova kartën, të lutem ma mbaj derën'.",
      question: "Çfarë taktike social engineering është kjo?",
      options: [
        { id: 1, text: "Tailgating - refuzo në mënyrë të sjellshme dhe udhëzo për procedurën e hyrjes", correct: true },
        { id: 2, text: "Kërkesë normale - ndihmoje", correct: false },
        { id: 3, text: "Koleg që ka nevojë", correct: false },
        { id: 4, text: "Vizitor legjitime", correct: false },
      ],
      explanation: "Tailgating shfrytëzon mirësjellshjen. Të gjithë duhet të përdorin aksesin e tyre.",
    },
    {
      id: 8,
      type: "mesazh",
      location: "ambjent",
      content: "Merrni kërkesë miqësie në Facebook nga dikush që pretendon të jetë ish-koleg, por profili është i ri.",
      question: "Çfarë duhet të bëni?",
      options: [
        { id: 1, text: "Pranoj menjëherë", correct: false },
        { id: 2, text: "E bllokój pa verifikuar", correct: false },
        { id: 3, text: "Pranoj por kufizoj çfarë sheh", correct: false },
        { id: 4, text: "Verifikoj identitetin nëpër kanali tjetër para pranimit", correct: true },
      ],
      explanation: "Sulmuesit krijojnë profile false për të mbledhur informacion. Verifikoni gjithmonë.",
    },
    {
      id: 9,
      type: "ndodhi",
      location: "security",
      content: "Vëreni që dikush po shikon mbi supet tuaja kur jeni duke shkruar fjalëkalimin.",
      question: "Çfarë taktike është kjo dhe si reagoni?",
      options: [
        { id: 1, text: "Kuriozitet normal - vazhdoj punën", correct: false },
        { id: 2, text: "Shoulder surfing - mbroj ekranin, ndërro fjalëkalimin nëse u pa", correct: true },
        { id: 3, text: "Koleg që kërkon ndihmë", correct: false },
        { id: 4, text: "Verifikim sigurie", correct: false },
      ],
      explanation: "Shoulder surfing vjedh informacion duke shikuar. Mbroni gjithmonë ekranin.",
    },
    {
      id: 10,
      type: "pyetje",
      location: "laborator",
      content: "Mësuesi pyet: 'Pse duhet të jem i kujdesshëm me çfarë postoj në rrjetet sociale?'",
      question: "Pse informacioni personal në rrjete sociale mund të jetë i rrezikshëm?",
      options: [
        { id: 1, text: "Nuk ka rrezik, janë profile private", correct: false },
        { id: 2, text: "Vetëm nëse ndani fjalëkalime", correct: false },
        { id: 3, text: "Sulmuesit e përdorin për të krijuar sulme të personalizuara (spear phishing)", correct: true },
        { id: 4, text: "Vetëm nëse keni shumë miq", correct: false },
      ],
      explanation: "Informacioni personal përdoret për spear phishing dhe sulme të targetuara.",
    },
  ],
  testQuestions: [
    {
      id: 1,
      question: "Çfarë është social engineering?",
      options: [
        { id: 1, text: "Inxhinieri softuerike", correct: false },
        { id: 2, text: "Manipulim psikologjik për të marrë informacion ose akses", correct: true },
        { id: 3, text: "Dizajn i rrjeteve sociale", correct: false },
        { id: 4, text: "Programim", correct: false },
      ],
    },
    {
      id: 2,
      question: "Çfarë është phishing?",
      options: [
        { id: 1, text: "Lloj peshkimi", correct: false },
        { id: 2, text: "Virus", correct: false },
        { id: 3, text: "Sulm që përdor email/mesazhe false për të vjedhur informacion", correct: true },
        { id: 4, text: "Firewall", correct: false },
      ],
    },
    {
      id: 3,
      question: "Çfarë është pretexting?",
      options: [
        { id: 1, text: "Shkrim i teksteve", correct: false },
        { id: 2, text: "Enkriptim", correct: false },
        { id: 3, text: "Backup", correct: false },
        { id: 4, text: "Krijim i një skenari/identiteti false për të marrë akses", correct: true },
      ],
    },
    {
      id: 4,
      question: "Çfarë është baiting?",
      options: [
        { id: 1, text: "Karrem për peshkim", correct: false },
        { id: 2, text: "Përdorimi i diçkaje joshëse (si USB) për të shpërndarë malware", correct: true },
        { id: 3, text: "Reklamë", correct: false },
        { id: 4, text: "Email marketing", correct: false },
      ],
    },
    {
      id: 5,
      question: "Çfarë është tailgating?",
      options: [
        { id: 1, text: "Hyrje në zonë të sigurt duke ndjekur dikë të autorizuar", correct: true },
        { id: 2, text: "Lloj enkriptimi", correct: false },
        { id: 3, text: "Backup", correct: false },
        { id: 4, text: "Ndjekje makinash", correct: false },
      ],
    },
    {
      id: 6,
      question: "Çfarë është shoulder surfing?",
      options: [
        { id: 1, text: "Sport ujor", correct: false },
        { id: 2, text: "Vjedhje informacioni duke shikuar mbi supin e dikujt", correct: true },
        { id: 3, text: "Lloj phishing", correct: false },
        { id: 4, text: "Virus", correct: false },
      ],
    },
    {
      id: 7,
      question: "Si mbroheni nga CEO Fraud?",
      options: [
        { id: 1, text: "Duke ju besuar çdo emaili nga shefi", correct: false },
        { id: 2, text: "Duke injoruar emailet", correct: false },
        { id: 3, text: "Duke verifikuar kërkesat e pazakonshme nëpër kanali tjetër", correct: true },
        { id: 4, text: "Duke ndërruar email", correct: false },
      ],
    },
    {
      id: 8,
      question: "Pse janë të rrezikshme linket e shkurtuara (bit.ly, etj)?",
      options: [
        { id: 1, text: "Sepse janë të gjata", correct: false },
        { id: 2, text: "Sepse fshihin destinacionin e vërtetë", correct: true },
        { id: 3, text: "Sepse janë të ngadalta", correct: false },
        { id: 4, text: "Nuk janë të rrezikshme", correct: false },
      ],
    },
    {
      id: 9,
      question: "Çfarë duhet të bëni nëse dikush kërkon informacion 'urgjent' nëpër telefoni?",
      options: [
        { id: 1, text: "Jepni menjëherë sepse është urgjent", correct: false },
        { id: 2, text: "Jepni vetëm pak informacion", correct: false },
        { id: 3, text: "Thirrni policinë", correct: false },
        { id: 4, text: "Mos jepni dhe verifikoni nëpër kanaleve zyrtare", correct: true },
      ],
    },
    {
      id: 10,
      question: "Si mund të përdoret informacioni në rrjetet sociale kundër jush?",
      options: [
        { id: 1, text: "Për të krijuar sulme spear phishing të personalizuara", correct: true },
        { id: 2, text: "Vetëm për reklama", correct: false },
        { id: 3, text: "Vetëm nga miqtë", correct: false },
        { id: 4, text: "Nuk përdoret", correct: false },
      ],
    },
  ],
  elaborationQuestion: {
    question:
      "Hartoni një program trajnimi për stafin mbi njohjen dhe parandalimin e sulmeve social engineering. Përfshini llojet e sulmeve dhe masat mbrojtëse.",
    keywords: [
      "phishing",
      "pretexting",
      "baiting",
      "tailgating",
      "verifikim",
      "trajnim",
      "ndërgjegjësim",
      "email",
      "telefon",
      "urgjencë",
      "autoritet",
      "kuriozitet",
      "raportim",
      "procedurë",
      "identitet",
    ],
  },
}
