import type { SimulationData } from "./index"

export const simulation4: SimulationData = {
  id: 4,
  title: "Siguria e Fjalëkalimeve dhe Autentikimit",
  description: "Praktika të sigurta për menaxhimin e fjalëkalimeve dhe autentikimit",
  icon: "Lock",
  context: "Ju jeni përgjegjës për sigurinë e llogarive dhe autentikimit në sistemet e shkollës.",
  steps: [
    {
      id: 1,
      type: "pyetje",
      location: "laborator",
      content: "Një mësues kërkon ndihmë për të krijuar fjalëkalim për llogarinë e re të emailit.",
      question: "Cili fjalëkalim rekomandoni?",
      options: [
        { id: 1, text: "elbasan123", correct: false },
        { id: 2, text: "Shk0ll@Pr0f3s10n@l3_2024!", correct: true },
        { id: 3, text: "password", correct: false },
        { id: 4, text: "12345678", correct: false },
      ],
      explanation: "Fjalëkalimet e forta përmbajnë shkronja, numra, simbole dhe janë të gjata.",
    },
    {
      id: 2,
      type: "situate",
      location: "security",
      content: "Zbuloni që 15 përdorues kanë fjalëkalimin 'Shkolla2024' për llogaritë e tyre.",
      question: "Çfarë veprimi merrni?",
      options: [
        { id: 1, text: "E lë si është sepse e mbajnë mend", correct: false },
        { id: 2, text: "Detyro ndërrimin e fjalëkalimit dhe eduko për fjalëkalime unike", correct: true },
        { id: 3, text: "Shtoj vetëm një numër në fund", correct: false },
        { id: 4, text: "Njoftoj vetëm administratorin", correct: false },
      ],
      explanation: "Fjalëkalimet e përbashkëta janë rrezik i madh. Çdo përdorues duhet fjalëkalim unik.",
    },
    {
      id: 3,
      type: "ndodhi",
      location: "ambjent",
      content: "Vëreni një post-it me fjalëkalimin e shkruar në monitorin e një kompjuteri në laborator.",
      question: "Çfarë bëni?",
      options: [
        { id: 1, text: "E lë sepse është i përdoruesit", correct: false },
        { id: 2, text: "E heq, detyro ndërrimin e fjalëkalimit dhe eduko përdoruesin", correct: true },
        { id: 3, text: "E fotografoj për arkivë", correct: false },
        { id: 4, text: "E vendos në sirtarin e tavolinës", correct: false },
      ],
      explanation: "Fjalëkalimet nuk duhet shkruar kurrë në vende të dukshme.",
    },
    {
      id: 4,
      type: "telefonata",
      location: "laborator",
      content:
        "Dikush telefonon duke thënë se është nga IT dhe kërkon fjalëkalimin tuaj për të 'zgjidhur një problem'.",
      question: "Si përgjigjeni?",
      options: [
        { id: 1, text: "I jap fjalëkalimin sepse është nga IT", correct: false },
        { id: 2, text: "Refuzoj dhe verifikoj me departamentin IT nëpërjet kanaleve zyrtare", correct: true },
        { id: 3, text: "I jap vetëm username", correct: false },
        { id: 4, text: "I them ta resetojë vetë", correct: false },
      ],
      explanation: "IT legjitime nuk kërkon kurrë fjalëkalime. Ky është sulm social engineering.",
    },
    {
      id: 5,
      type: "mesazh",
      location: "security",
      content: "Sistemi tregon që llogaria e administratorit nuk ka 2FA (autentikim me dy faktorë) të aktivizuar.",
      question: "Çfarë veprimi merrni?",
      options: [
        { id: 1, text: "E lë sepse fjalëkalimi është i fortë", correct: false },
        { id: 2, text: "Aktivizoj 2FA menjëherë dhe e bëj të detyrueshëm për llogari kritike", correct: true },
        { id: 3, text: "Ndërroj vetëm fjalëkalimin", correct: false },
        { id: 4, text: "Shto pytje sigurie", correct: false },
      ],
      explanation: "2FA shton shtresë shtesë sigurie edhe nëse fjalëkalimi kompromutohet.",
    },
    {
      id: 6,
      type: "situate",
      location: "laborator",
      content: "Një nxënës ka harruar fjalëkalimin dhe kërkon ta resetoni pa verifikuar identitetin.",
      question: "Si veproni?",
      options: [
        { id: 1, text: "E resetoj menjëherë sepse e njoh", correct: false },
        { id: 2, text: "Verifikoj identitetin me dokument ose email sekondar para reset", correct: true },
        { id: 3, text: "I jap fjalëkalimin e dikujt tjetër përkohësisht", correct: false },
        { id: 4, text: "I them të presë derisa mësuesi të konfirmojë", correct: false },
      ],
      explanation: "Verifikimi i identitetit është i domosdoshëm para çdo reset fjalëkalimi.",
    },
    {
      id: 7,
      type: "tekst",
      location: "ambjent",
      content: "Vëreni që sistemi lejon fjalëkalime me vetëm 4 karaktere pa kërkesa kompleksiteti.",
      question: "Çfarë rekomandoni?",
      options: [
        { id: 1, text: "E lë si është për lehtësi", correct: false },
        { id: 2, text: "Implementoj politikë: min 12 karaktere, shkronja, numra, simbole", correct: true },
        { id: 3, text: "Rris në 6 karaktere", correct: false },
        { id: 4, text: "Shtoj vetëm kërkesë për numra", correct: false },
      ],
      explanation: "Politikat e forta të fjalëkalimeve parandalojnë sulmet brute-force.",
    },
    {
      id: 8,
      type: "ndodhi",
      location: "security",
      content: "Zbulohet se disa mësues ndajnë të njëjtën llogari administratori për të menaxhuar notat.",
      question: "Çfarë problemi paraqet kjo dhe si e zgjidhni?",
      options: [
        { id: 1, text: "Nuk ka problem sepse janë mësues", correct: false },
        { id: 2, text: "Krijoni llogari individuale me role të përshtatshme dhe auditim", correct: true },
        { id: 3, text: "Ndërroni fjalëkalimin më shpesh", correct: false },
        { id: 4, text: "Shtoni ende një përdorues në llogari", correct: false },
      ],
      explanation: "Llogaritë e përbashkëta pamundësojnë auditimin dhe rrisin rrezikun.",
    },
    {
      id: 9,
      type: "mesazh",
      location: "laborator",
      content: "Merrni kërkesë nga mësuesi për të ruajtur fjalëkalimin e ri në browser për 'lehtësi'.",
      question: "Çfarë rekomandoni?",
      options: [
        { id: 1, text: "Po, ruaje në browser", correct: false },
        { id: 2, text: "Përdor password manager të sigurt në vend të browser", correct: true },
        { id: 3, text: "Shkruaje në fletore", correct: false },
        { id: 4, text: "Dërgo me email vetes", correct: false },
      ],
      explanation: "Password managers janë më të sigurt se ruajtja në browser.",
    },
    {
      id: 10,
      type: "situate",
      location: "security",
      content:
        "Loget tregojnë login të suksesshëm nga një vend i pazakontë (në një shtet tjetër) në llogarinë e administratorit.",
      question: "Si reagoni?",
      options: [
        { id: 1, text: "Injoroj sepse login ishte i suksesshëm", correct: false },
        { id: 2, text: "Bllokoj sesionin, ndërroj fjalëkalimin, aktivizoj 2FA dhe hetoj", correct: true },
        { id: 3, text: "Kontaktoj përdoruesin nesër", correct: false },
        { id: 4, text: "Shtoj IP-në në whitelist", correct: false },
      ],
      explanation: "Login nga vendndodhje e pazakontë mund të tregojë kompromitim të llogarisë.",
    },
  ],
  testQuestions: [
    {
      id: 1,
      question: "Sa karaktere duhet të ketë minimumi një fjalëkalim i fortë?",
      options: [
        { id: 1, text: "4", correct: false },
        { id: 2, text: "12 ose më shumë", correct: true },
        { id: 3, text: "6", correct: false },
        { id: 4, text: "8", correct: false },
      ],
    },
    {
      id: 2,
      question: "Çfarë është 2FA?",
      options: [
        { id: 1, text: "Dy fjalëkalime", correct: false },
        { id: 2, text: "Dy llogari", correct: false },
        { id: 3, text: "Autentikim me dy faktorë të ndryshëm", correct: true },
        { id: 4, text: "Dy pyetje sigurie", correct: false },
      ],
    },
    {
      id: 3,
      question: "Pse nuk duhet ripërdorur fjalëkalimet?",
      options: [
        { id: 1, text: "Sepse harrohen", correct: false },
        { id: 2, text: "Sepse janë të gjata", correct: false },
        { id: 3, text: "Nuk ka problem të ripërdoren", correct: false },
        { id: 4, text: "Sepse nëse kompromutohet një, rrezikohen të gjitha", correct: true },
      ],
    },
    {
      id: 4,
      question: "Çfarë është password manager?",
      options: [
        { id: 1, text: "Person që menaxhon fjalëkalimet", correct: false },
        { id: 2, text: "Softuer që ruan dhe gjeneron fjalëkalime të sigurta", correct: true },
        { id: 3, text: "Fletore për fjalëkalime", correct: false },
        { id: 4, text: "Email për fjalëkalime", correct: false },
      ],
    },
    {
      id: 5,
      question: "Kur duhet ndërruar fjalëkalimin?",
      options: [
        { id: 1, text: "Kur dyshoni kompromitim ose periodikisht sipas politikës", correct: true },
        { id: 2, text: "Çdo ditë", correct: false },
        { id: 3, text: "Vetëm kur e harroni", correct: false },
        { id: 4, text: "Kurrë", correct: false },
      ],
    },
    {
      id: 6,
      question: "Cilat karaktere duhet të përmbajë fjalëkalimi i fortë?",
      options: [
        { id: 1, text: "Vetëm shkronja", correct: false },
        { id: 2, text: "Shkronja të mëdha, të vogla, numra dhe simbole", correct: true },
        { id: 3, text: "Vetëm numra", correct: false },
        { id: 4, text: "Vetëm shkronja të vogla", correct: false },
      ],
    },
    {
      id: 7,
      question: "Pse janë të rrezikshme llogaritë e përbashkëta?",
      options: [
        { id: 1, text: "Sepse janë të shtrenjta", correct: false },
        { id: 2, text: "Sepse janë të ngadalta", correct: false },
        { id: 3, text: "Nuk janë të rrezikshme", correct: false },
        { id: 4, text: "Sepse pamundësojnë auditimin dhe rrisin rrezikun e kompromitimit", correct: true },
      ],
    },
    {
      id: 8,
      question: "Çfarë duhet të bëni nëse dikush kërkon fjalëkalimin tuaj me telefon?",
      options: [
        { id: 1, text: "Ja jepni nëse duket legjitime", correct: false },
        { id: 2, text: "Refuzoni dhe verifikoni nëpërjet kanaleve zyrtare", correct: true },
        { id: 3, text: "I thoni ta dërgojë me email", correct: false },
        { id: 4, text: "Ja jepni pjesërisht", correct: false },
      ],
    },
    {
      id: 9,
      question: "Cila është praktika më e mirë për pyetjet e sigurisë?",
      options: [
        { id: 1, text: "Përdorni përgjigje të vërteta që mund të gjenden online", correct: false },
        { id: 2, text: "Përdorni të njëjtën përgjigje kudo", correct: false },
        { id: 3, text: "Mos përdorni pyetje sigurie", correct: false },
        { id: 4, text: "Përdorni përgjigje të rreme ose unike që vetëm ju i dini", correct: true },
      ],
    },
    {
      id: 10,
      question: "Çfarë tregon login nga vendndodhje e pazakontë?",
      options: [
        { id: 1, text: "Mundësi kompromitimi që duhet hetuar", correct: true },
        { id: 2, text: "Gabim sistemi", correct: false },
        { id: 3, text: "VPN i përdoruesit", correct: false },
        { id: 4, text: "Përdorim normal", correct: false },
      ],
    },
  ],
  elaborationQuestion: {
    question:
      "Hartoni një politikë të plotë të fjalëkalimeve për shkollën. Përfshini kompleksitetin, ndërrimin, 2FA dhe trajnimin e përdoruesve.",
    keywords: [
      "kompleksitet",
      "karaktere",
      "numra",
      "simbole",
      "2FA",
      "unik",
      "password manager",
      "ndërroj",
      "politikë",
      "trajnim",
      "verifikim",
      "auditim",
      "llogari",
      "sigurie",
      "brute-force",
    ],
  },
}
