import type { SimulationData } from "./index"

export const simulation6: SimulationData = {
  id: 6,
  title: "Siguria e të Dhënave dhe Privatësia",
  description: "Mbrojtja e të dhënave personale dhe konfidenciale të shkollës",
  icon: "Database",
  context: "Ju jeni përgjegjës për sigurinë e të dhënave të nxënësve dhe stafit në shkollë.",
  steps: [
    {
      id: 1,
      type: "situate",
      location: "laborator",
      content:
        "Gjeni një skedar Excel me notat dhe të dhënat personale të 500 nxënësve në desktopun e kompjuterit të përbashkët.",
      question: "Çfarë veprimi merrni?",
      options: [
        { id: 1, text: "E lë sepse është i dobishëm", correct: false },
        { id: 2, text: "E dërgoj me email vetes", correct: false },
        { id: 3, text: "E riemërtoj për ta fshehur", correct: false },
        { id: 4, text: "E zhvendos në server të sigurt me akses të kufizuar dhe fshij kopjen lokale", correct: true },
      ],
      explanation: "Të dhënat personale duhet ruajtur në sisteme të sigurta me akses të kontrolluar.",
    },
    {
      id: 2,
      type: "telefonata",
      location: "laborator",
      content: "Dikush telefonon duke thënë se është prind dhe kërkon notat e fëmijës nëpërjet telefonit.",
      question: "Si veproni?",
      options: [
        { id: 1,
          text: "Refuzoj të jap informacion nëpërjet telefonit dhe udhëzoj për procedurën zyrtare",
          correct: true },
        { id: 2, text: "I jap notat menjëherë", correct: false },
        { id: 3, text: "I kërkoj emrin e fëmijës dhe ia dërgoj me email", correct: false },
        { id: 4, text: "I jap notat nëse tregon numrin e telefonit të regjistruar", correct: false },
      ],
      explanation: "Informacioni personal nuk jepet nëpërjet telefonit pa verifikim të sigurt.",
    },
    {
      id: 3,
      type: "mesazh",
      location: "security",
      content: "Merrni email me kërkesë për listën e emaileve të të gjithë mësuesve 'për një konferencë arsimore'.",
      question: "Si përgjigjeni?",
      options: [
        { id: 1, text: "Dërgoj listën menjëherë", correct: false },
        {
          id: 2,
          text: "Verifikoj identitetin dhe qëllimin, dhe ndjek procedurën e shkollës për ndarjen e të dhënave",
          correct: true,
        },
        { id: 3, text: "Dërgoj vetëm disa emaile", correct: false },
        { id: 4, text: "E injoroj emailin", correct: false },
      ],
      explanation: "Kërkesat për të dhëna duhet verifikuar dhe ndjekur procedurat e shkollës.",
    },
    {
      id: 4,
      type: "ndodhi",
      location: "ambjent",
      content: "Vëreni që printeri i përbashkët ka letra të printuara me lista notash që askush nuk i mori.",
      question: "Çfarë bëni?",
      options: [
        { id: 1, text: "I mbledh dhe i asgjësoj në mënyrë të sigurt (shredder)", correct: true },
        { id: 2, text: "I lë atje sepse dikush do ti marrë", correct: false },
        { id: 3, text: "I vendos në tavolinë", correct: false },
        { id: 4, text: "I lexoj dhe i lë", correct: false },
      ],
      explanation: "Dokumentet me të dhëna personale duhet asgjësuar në mënyrë të sigurt.",
    },
    {
      id: 5,
      type: "pyetje",
      location: "laborator",
      content: "Mësuesi pyet: 'A mund të përdor Google Drive personal për të ruajtur notat e nxënësve?'",
      question: "Çfarë rekomandoni?",
      options: [
        { id: 1, text: "Po, është i sigurt", correct: false },
        { id: 2, text: "Po, me enkriptim", correct: false },
        { id: 3, text: "Po, por mos i ndani me askënd", correct: false },
        { id: 4, text: "Jo, përdorni vetëm sistemet e aprovuara nga shkolla për të dhëna zyrtare", correct: true },
      ],
      explanation: "Të dhënat zyrtare duhet ruajtur vetëm në sistemet e aprovuara nga institucioni.",
    },
    {
      id: 6,
      type: "situate",
      location: "security",
      content: "Zbulohet se një ish-punonjës ende ka akses në sistemin e notave pas largimit nga puna.",
      question: "Çfarë duhet të bëhej dhe çfarë bëni tani?",
      options: [
        { id: 1, text: "E lë sepse nuk ka dëmtuar gjë", correct: false },
        { id: 2, text: "Revokoi aksesin menjëherë dhe implementoj procedurë offboarding të rreptë", correct: true },
        { id: 3, text: "I dërgoj email duke i kërkuar të mos hyjë", correct: false },
        { id: 4, text: "Ndërroj vetëm fjalëkalimin e tij", correct: false },
      ],
      explanation: "Aksesi duhet revokuar menjëherë kur punonjësi largohet. Procedura offboarding parandalon këtë.",
    },
    {
      id: 7,
      type: "tekst",
      location: "laborator",
      content: "Një nxënës kërkon të shohë notat e shokut 'sepse janë miq të mirë'.",
      question: "Si përgjigjeni?",
      options: [
        { id: 1, text: "I tregoj sepse janë në të njëjtën klasë", correct: false },
        { id: 2, text: "I tregoj vetëm notat pozitive", correct: false },
        { id: 3, text: "Refuzoj - çdo nxënës ka të drejtë vetëm për të dhënat e veta", correct: true },
        { id: 4, text: "I them të pyes mësuesin", correct: false },
      ],
      explanation: "Privatësia e të dhënave personale duhet respektuar. Çdokush ka akses vetëm në të dhënat e veta.",
    },
    {
      id: 8,
      type: "mesazh",
      location: "security",
      content: "Një mësues dëshiron të postojë foto të klasës në Facebook duke përfshirë fëmijë.",
      question: "Çfarë duhet të marrë parasysh?",
      options: [
        { id: 1, text: "Asgjë, janë foto të bukura", correct: false },
        { id: 2, text: "Nuk ka rëndësi sepse është profil privat", correct: false },
        { id: 3, text: "Mjafton pëlqimi i fëmijëve", correct: false },
        { id: 4, text: "Duhet marrë pëlqimin e prindërve para postimit të fotove të fëmijëve", correct: true },
      ],
      explanation: "Fotot e fëmijëve kërkojnë pëlqim të prindërve para publikimit në rrjete sociale.",
    },
    {
      id: 9,
      type: "ndodhi",
      location: "pajisje",
      content: "Një USB me backup të të dhënave të shkollës humbet në rrugë.",
      question: "Çfarë duhet të kishte bërë dhe çfarë bëni tani?",
      options: [
        { id: 1,
          text: "USB duhej enkriptuar. Tani raportoj incidentin dhe vlerësoj të dhënat e komprometuara",
          correct: true, },
        { id: 2, text: "Asgjë, do ta gjejë dikush", correct: false },
        { id: 3, text: "Krijoj backup të ri", correct: false },
        { id: 4, text: "Shpresoj të mos hapet", correct: false },
      ],
      explanation: "Pajisjet portable me të dhëna duhet enkriptuar. Humbja duhet raportuar si incident.",
    },
    {
      id: 10,
      type: "situate",
      location: "serveroom",
      content: "Zbuloni se baza e të dhënave e studentëve nuk ka enkriptim dhe aksesohet me kredenciale të dobëta.",
      question: "Çfarë rreziqesh ka dhe çfarë masash merrni?",
      options: [
        { id: 1, text: "Nuk ka rrezik sepse është në server lokal", correct: false },
        { id: 2, text: "Ndërroj vetëm fjalëkalimin", correct: false },
        { id: 3,
          text: "Implementoj enkriptim, kredenciale të forta, logim aksesi dhe backup të enkriptuar",
          correct: true, },
        { id: 4, text: "Shtoj firewall", correct: false },
      ],
      explanation: "Të dhënat personale duhet enkriptuar në ruajtje dhe transit, me akses të kontrolluar.",
    },
  ],
  testQuestions: [
    {
      id: 1,
      question: "Çfarë janë të dhënat personale?",
      options: [
        { id: 1, text: "Vetëm emri", correct: false },
        { id: 2, text: "Vetëm numri i telefonit", correct: false },
        { id: 3, text: "Çdo informacion që mund të identifikojë një individ", correct: true },
        { id: 4, text: "Vetëm adresa", correct: false },
      ],
    },
    {
      id: 2,
      question: "Kush ka të drejtë të aksesojë notat e një nxënësi?",
      options: [
        { id: 1, text: "Çdokush në shkollë", correct: false },
        { id: 2, text: "Nxënësi, prindërit, mësuesit përkatës dhe administratorët e autorizuar", correct: true },
        { id: 3, text: "Vetëm drejtori", correct: false },
        { id: 4, text: "Të gjithë mësuesit", correct: false },
      ],
    },
    {
      id: 3,
      question: "Pse duhet enkriptuar pajisjet portable me të dhëna?",
      options: [
        { id: 1, text: "Për shpejtësi", correct: false },
        { id: 2, text: "Për estetikë", correct: false },
        { id: 3, text: "Nuk nevojitet", correct: false },
        { id: 4, text: "Për të mbrojtur të dhënat në rast humbjeje ose vjedhjeje", correct: true },
      ],
    },
    {
      id: 4,
      question: "Çfarë duhet të bëni me dokumentet me të dhëna personale që nuk nevojiten më?",
      options: [
        { id: 1, text: "I hidhni në kosh", correct: false },
        { id: 2, text: "I asgjësoni me shredder ose metoda të sigurta", correct: true },
        { id: 3, text: "I ruani në sirtar", correct: false },
        { id: 4, text: "I djegni", correct: false },
      ],
    },
    {
      id: 5,
      question: "A mund të postoni foto të nxënësve në rrjete sociale?",
      options: [
        { id: 1, text: "Vetëm me pëlqim të dokumentuar të prindërve", correct: true },
        { id: 2, text: "Po, nëse janë foto të bukura", correct: false },
        { id: 3, text: "Po, nëse janë foto grupi", correct: false },
        { id: 4, text: "Po, gjithmonë", correct: false },
      ],
    },
    {
      id: 6,
      question: "Çfarë është procedura offboarding?",
      options: [
        { id: 1, text: "Procedura e rekrutimit", correct: false },
        { id: 2, text: "Procedura e revokimit të aksesit kur punonjësi largohet", correct: true },
        { id: 3, text: "Procedura e trajnimit", correct: false },
        { id: 4, text: "Procedura e backup", correct: false },
      ],
    },
    {
      id: 7,
      question: "Ku duhet të ruhen të dhënat zyrtare të shkollës?",
      options: [
        { id: 1, text: "Në llogari personale cloud", correct: false },
        { id: 2, text: "Në USB personal", correct: false },
        { id: 3, text: "Vetëm në sistemet e aprovuara nga shkolla", correct: true },
        { id: 4, text: "Në email personal", correct: false },
      ],
    },
    {
      id: 8,
      question: "Çfarë duhet të bëni nëse humbisni pajisje me të dhëna?",
      options: [
        { id: 1, text: "Ta injoroni", correct: false },
        { id: 2, text: "Raportoni menjëherë si incident sigurie", correct: true },
        { id: 3, text: "Prisni ta gjeni", correct: false },
        { id: 4, text: "E zëvendësoni me pajisje të re", correct: false },
      ],
    },
    {
      id: 9,
      question: "Pse nuk jepen të dhëna nëpërjet telefonit?",
      options: [
        { id: 1, text: "Sepse është e vështirë", correct: false },
        { id: 2, text: "Sepse kushton", correct: false },
        { id: 3, text: "Jepen pa problem", correct: false },
        { id: 4, text: "Sepse nuk mund të verifikohet identiteti i kërkuesit", correct: true },
      ],
    },
    {
      id: 10,
      question: "Çfarë është GDPR/Mbrojtja e të Dhënave?",
      options: [
        { id: 1, text: "Rregullore për mbrojtjen e të dhënave personale të individëve", correct: true },
        { id: 2, text: "Lloj enkriptimi", correct: false },
        { id: 3, text: "Antivirus", correct: false },
        { id: 4, text: "Softuer backup", correct: false },
      ],
    },
  ],
  elaborationQuestion: {
    question:
      "Hartoni një politikë të mbrojtjes së të dhënave për shkollën. Përfshini ruajtjen, aksesin, ndarjen dhe asgjësimin e të dhënave.",
    keywords: [
      "enkriptim",
      "akses",
      "privatësi",
      "pëlqim",
      "backup",
      "offboarding",
      "shredder",
      "konfidencial",
      "GDPR",
      "password",
      "autorizim",
      "audit",
      "raportim",
      "incident",
      "ndarje",
    ],
  },
}
